services:
  - type: web
    name: beyondChats-backend
    env: python
    pythonVersion: 3.11   # Stable version compatible with PyMuPDF & psycopg2
    plan: starter          # Change if you need a higher plan
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-10000} --workers 4 --proxy-headers
    envVars: 
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: SUPABASE_URL
        value: "https://gsgiwpwyvfascngdjlfm.supabase.co"
      - key: SUPABASE_KEY
        value: "sb_secret_YhmFOf5rWfNgtRkoFU3aXg_ad9gUsc1"
